#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os
from subprocess import check_output

if os.path.exists("/home/user/.gateway"):
    if os.path.exists("/home/user/.gateway/first_use_check.done"):
        sys.exit(0)
    else:
        itype = "information"
        title = "First use notice"
        msg = """Welcome to Whonix-Gateway!
<p>This is NOT a personal work station for your own private activities! So please do NOT use Whonix-Gateway
for any purpose other than configuring Tor and Whonix.</p>
<p>The more you learn about Whonix and anonymity, the safer you can become. Reading Whonix documentation
is recommended.</p>
<p>If your host has little RAM, you are advised to reduce Whonix-Gateway RAM to 128 MB. No graphical desktop environment will be started in that case. A Whonix-Gateway without graphical desktop environment works as good as one with, it is just not that convenient. If you want, you can sometimes start a graphical desktop environment and sometimes only a terminal by toggling how much
RAM is available to Whonix-Gateway. Documentation about this feature: <a href=https://www.whonix.org/wiki/Desktop>https://www.whonix.org/wiki/Desktop</p>
<p>If you want to change the keyboard layout from the default \"us\" to something else:
<blockquote>Start menu button -> Applications -> Settings -> System Settings -> input devices -> layout ->
add yours and remove default one -> apply -> Done.</blockquote></p>
</p>Default username: user<br></br>Default password: changeme</p>"""
        question = "Show this message at startup?"
        button = "yesno"
        answer = int(check_output(["/usr/lib/generic_gui_message", itype, title, msg, question, button]))
        if answer == 65536: # button 'No' pressed
            f = open("/home/user/.gateway/first_use_check.done", "w")
            f.close()
